version: '3.8'

services:
  db:
    platform: linux/x86_64
    build: ./services/db
    image: postgres:13
    volumes:
      - ./:/tmp/db
      - $HOME/bigdata/pg_normalized:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres_dev
    ports:
      - 2089:5432

  web:
    build: ./services/web
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 1089:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:
